export const FILTER_BY_TEAM = "FILTER_BY_TEAM";
export const FILTER_BY_ORIGIN ="FILTER_BY_ORIGIN";
export const SORT_BY_DOB="SORT_BY_DOB";
export const SORT_BY_DRIVER_NAME="SORT_BY_DRIVER_NAME";
export const ALL_ORIGIN = "ALL_ORIGIN";
export const ALL_DRIVERS = "ALL_DRIVERS";
export const GET_DRIVER_BY_ID ="GET_DRIVER_BY_ID";
export const CREATE_NEW_DRIVER="CREATE_NEW_DRIVER";
export const GET_DRIVER_DETAIL_BY_ID ="GET_DRIVER_DETAIL_BY_ID";
export const ORDER_BY="ORDER_BY";
export const RESET_FILTERS = "RESET_FILTERS";
export const SORT_BY_NAME_ASC = 'SORT_BY_NAME_ASC';
export const SORT_BY_NAME_DESC = 'SORT_BY_NAME_DESC';
export const SORT_BY_DOB_ASC = 'SORT_BY_DOB_ASC';
export const SORT_BY_DOB_DESC = 'SORT_BY_DOB_DESC';
export const LOAD_DRIVERS_SUCCESS = 'LOAD_DRIVERS_SUCCESS';
export const LOAD_DRIVERS_FAILURE = 'LOAD_DRIVERS_FAILURE';
export const GET_ERROR_SEARCH = 'GET_ERROR_SEARCH';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_PAGES = ' SET_TOTAL_PAGES';
export const ALL_TEAMS = 'ALL_TEAMS';
export const IS_LOADING = 'IS_LOADING';
 
 